jenkinsci/jenkins-multijob-plugin

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
This patch simplify the getScmChange method, making it more Jenkins friendly, and minimizing the complexity of decisions.
> Fix the polling method, making it more Jenkins API - friendly

- pom.xml
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuildSelector.java
- src/main/resources/com/tikal/jenkins/plugins/multijob/Messages.properties
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuildSelector/config.jelly
- src/main/webapp/help-copyArtifact.html
- src/test/java/com/tikal/jenkins/plugins/multijob/test/testutils/FileWriteBuilder.java
THIS IS AN INTEGRATION WITH Copy Artifact Plugin.
-Added a new Build Selector called MultiJobBuildSelector
to CopyArtifact Build Selector.
-If selected, this will make the Copy Artifact Plugin look
for an artifact from that job's build which was part of the
current MultiJobBuild.
-This selector will work properly if you configure it with
a MultiJobProject which has a PhaseJob that archives an
artifact that you want to retrieve as part of the MultiJob.
-This selector will also work if you configure it to Copy an
Artifact from another Phase Job which was part of the
current MultiJob Build.
-Added tests to ensure this functionality works as expected.
-Adds CopyArtifact Plugin as an optional dependency.
-Updated Jenkins dependency to use v1.509.
> [JENKINS-25111] Copy Artifacts from Phase Job

- src/main/java/com/tikal/jenkins/plugins/multijob/views/MultiJobListViewColumn.java
Jenkins is showing Status column as 1st Column. 
We are using "Canon-Rackspace" theme on our Jenkins environment.
Which consider 1st column as status column and apply status specific css on 1st column, which is in case of Multi job is job name.
As a consistency in Jenkins we should maintain it or have a flexibility to make it compatible.
> Re arranging column, in same as viewed with Jenkins

- src/main/resources/com/tikal/jenkins/plugins/multijob/views/JobColumn/column.jelly
https://issues.jenkins-ci.org/browse/JENKINS-30262
The change replaces the implementation to Job's absolute url in order to always produce a valid link. The original approach does not work in general, because Views may not contain the multijob's items => relative paths may be broken.
Ridiculously, there's the same glitch in /lib/hudson/jobLink for the supported version core. It needs to be investigated separately.
@reviewbybees @hagzag
> [FIXED JENKINS-30262] - Always use absolute URLs in MultiJob's JobColumn

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
There is a bug in addBuildEnvironmentVariables that means that some of the variables are not updated correctly. The code creates an empty HashMap every time it is executed, but is attempting to find variables in it from previous calls.
The fix is to pull the existing environment variables into the local HashMap at the start of addBuildEnvironmentVariables.
I addition, I've added some extra variables - [job name]_[run instance]_BUILD_NUMBER/RESULT (one for each instance of a job when run multiple times) - similar to the ones used in the parameterized trigger plugin. The variables are only added when a job is run multiple times.
Neither of these changes affect the existing [job name]_BUILD_NUMBER/RESULT variables, which still reference the last job executed, so shouldn't break compatibility …
> [JENKINS-29229] Fixed (and added) environment variables

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobResumeBuild.java
Fix for 
>> shacharbz commented 2 hours ago
Hi @sshelomentsev
I have a problem with re-running a failed job
If my build is parameterized, the resumed build won't use the params I passed in the initial run.
> Reuse parameters for parameterized builds

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
Let we have several jobs in one phase. Each job is configured not to abort the remaining jobs.
But currently, if one of these jobs completed with status FAILED, then other jobs are cancelled.
So, if "Abort all other jobs" isn't checked then the remianing jobs should continue execution
(http://s21.postimg.org/3pixtinuv/Screen_Shot_2015_11_17_at_15_02_34.png)
> Other jobs should be aborted only if it configured in phase

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
- src/main/java/com/tikal/jenkins/plugins/multijob/PhaseJobsConfig.java
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuilder/config.jelly
- src/main/webapp/help-applyCondition.html
- src/test/java/com/tikal/jenkins/plugins/multijob/test/ConditionalPhaseTest.java
- src/test/java/com/tikal/jenkins/plugins/multijob/test/PhaseJobsConfigTest.java
This is good for scenarios where you check the "Build only if SCM changes" and you have a condition enabled, but you want the condition to be evaluated only if there were no SCM changes.
If SCM changes were found, the build should run regardless of the condition.
> add an option to eval the phase condition only when no SCM changes were found

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuild.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
Hi,
I have adapted the resume build feature (#73) to include any job which did not result in SUCCESS. Previously it would only rebuild FAILED jobs and link to the previous build for UNSTABLE or ABORTED jobs.
@sshelomentsev: I'd appreciate if you can review the modifications I have made
Thanks
> Resume build to include UNSTABLE and ABORTED jobs

- src/main/resources/com/tikal/jenkins/plugins/multijob/views/ConsoleColumn/column.jelly
In the landing page for a Multijob, the link to console output for sub jobs or steps is broken when
* You navigate to it from a non-default view
* and the sub job is in a Folder
This is because the console link uses baseUrl+shortUrl instead of directly using absoluteUrl. 
Steps to reproduce is mentioned in a related issue which is fixed now. [Issue 30262](https://issues.jenkins-ci.org/browse/JENKINS-30262)
> Use absolute url for console link

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
If a single parameterized job is used multiple times (with different
parameters) in the same phase, and that parameterized job is properly set
up to "Execute concurrent builds if necessary", race conditions when
getting / putting the environment variables may occur.
In my test case, I've crerated a (very short running) parameterized job
called "Run-Test-Part". Although I'm running that job 4 times with
different parameters within the same phase, I got
TRIGGERED_BUILD_RUN_COUNT_RUN_TEST_PART=2
instead of the expected value of 4, because differnet threads passed the
variables.get("TRIGGERED_BUILD_RUN_COUNT_" + jobNameSafe) != null
check before the variable was put / injected into the environment.
This commit fixes that issue by synchronizing the
addBuildEnvironmentVariables() method.
> MultiJobBuilder: Synchronize adding the build environment variables

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuildSelector.java
As mentioned in a comment of the JENKINS-25111 issue, the Multijob build selector does not work when using folders. The problem is due to the use of getFullDisplayName() instead of getDisplayName() when looking for a SubBuild. getFullDisplayName() includes the parent names (i.e. "folder > job_name") whereas sub build's job name contains only the job name (i.e. "job_name"). Using getDisplayName(), we always compare job names with job names.
> [JENKINS-25111] Fix problem in MultijobBuildSelector when using folders

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuild.java
This change was driven by a need on my team to surface NOT_BUILT as the actual 
build result in order to affect how the Jenkins Gerrit trigger plugin votes on 
a code review. When NOT_BUILT is passed back, no negative or positive action is 
taken on a code review. How we use this is to examine certain aspects of what was 
changed in a review and how it relates to the artifacts we need to generate.  
If certain conditions are met, then we set a job's result to NOT_BUILT to
indicate that no build action is required.
I realized this may be too specialized for general use, but I wanted to offer it up regardless.
> Support for NOT_BUILT build result

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
- src/main/java/com/tikal/jenkins/plugins/multijob/SubTask.java
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuilder/config.jelly
- src/main/webapp/help-executionType.html
- src/test/java/com/tikal/jenkins/plugins/multijob/test/ConditionalPhaseTest.java
Hi everyone,
I've implemented a feature that allows you to select the type of execution jobs in a phase.
This two options: parallel and sequentially. Running in parallel fully coincides with current execution logic. In the sequential case next job starts after the end of the previous one. The decision to launch the next job is based on phase configuration.
Hope, my request is clear.
> Execution type for multiple jobs in a phase: parallel or sequentially.

- pom.xml
- src/main/java/com/tikal/jenkins/plugins/multijob/views/MultiJobView.java
I want to use ezTemplate Plugin which is used for templating jobs.
EzTemplate plugin is very useful for use as templated job, It has a similar functionality as conditional buildstep plugin.
As we can see Multijob view for conditional build steps. 
As this plugin has a custom implementation to view conditional build step.
I also want to add same behavior for ezTemplate plugin.
There is a side impact that is :We will have another dependency for ezTemplate plugin in this plugin. :-1: 
For reference :
https://github.com/JoelJ/ez-templates/issues/52
https://github.com/JoelJ/ez-templates/pull/54
> EzTemplate (similar to Conditional Plugin) support added

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobProject.java
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobProject/configure-entries.jelly
- src/main/webapp/help-resumesamevars.html
Hi,
I've added a new option to the configuration page to verify that environment variables are identical when resuming a build.
This can be used to validate the build we are resuming from is in a consistent state with the workspace. e.g.: GIT_COMMIT
When the variable valuess are different, a full build is triggered instead.
This property is optional, therefore the current behavior is maintained.
Cheers,
> Verify env variables are identical on resume

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
storing the build object means that it needs to be serialized when
actions are serialized, and this can cause spurious failures
(CuncurrentModificationException) if something else is trying to modify
the build object's subBuildMap at the same time.
> just store the build number rather than the build object on the action

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
For heavy users of this plugin, upgrading the plugin exposes users to
an unhandled backwards incompatibility in the data persistence format.
In our case, it caused the OldDataMonitor object to become flooded with
error messages from trying to load old jobs, to the point of slowly but
surely filling up as much heap as we could throw at Jenkins due to the
large number of builds we have using this plugin.
This change implements the readResolve method used by the XStream
persistence layer to convert old build data to the new version, as
described in the Jenkins documentation. See the linked Jenkins help page
in code comments for more details.
The original backwards incompatibility was found here: https://github.com/jenkinsci/tikal-multijob-plugin/pull/97 after finding a very large number of …
> Fix backwards compatibility bug with old build data

- RetryFailedSubjobs.md
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
When a subjob is marked as `UNSTABLE`, the retry strategy would not trigger. It only triggers when the subjob result is `FAILURE` or worse. This pull request changes the functionality to trigger the retry strategy when the result is `UNSTABLE` or worse. 
Existing users who would want to disable this change could update their Retry Strategy rules to include:
```Finished: FAILURE```
Additionally this PR adds documentation describing how to set up the Retry Strategy rules.
> Trigger retry rules when Job result is UNSTABLE or worse, instead of FAILURE or worse

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobParametersAction.java
- src/test/java/com/tikal/jenkins/plugins/multijob/test/MultiJobParametersActionTest.java
Just a quick bugfix with a set of direct unit tests for the related functionality. The issue itself comes from the partially correct fix of JENKINS-36124 in #100, which was a SECURITY-170 fix attempt.
Functional tests are available in #106
https://issues.jenkins-ci.org/browse/JENKINS-38850
@reviewbybees @cohencil @t0r0X @aheritier
> [FIXED JENKINS-38850] - Pass params to ParametersAction to fix shouldSchedule()

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
Fixing a bug that was retrying twice the number specified for maxretries field. _E.g. if I specify "1" in maxretry field, it triggers the phase job twice. This was a big headache for us as our job runs for 90 min and if it fails the retry option trigger's it twice and it accounts only the result of 2nd job, so the multijob waits for approx 180 min to get result of retry job._ 
subTask.generateFuture() is executed twice for every retry attempt and hence twice the number of jobs get triggered. I believe subTask.isShouldTrigger() never becomes false hence subTask.generateFuture() runs twice.
Change-Id: I123b1d16b947305b8dd96da6d1ca6d8a5ef7762e
> Fixing a bug that was retrying twice the number specified for maxretries field.

- pom.xml
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuild.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
- src/main/java/com/tikal/jenkins/plugins/multijob/PhaseJobsConfig.java
- src/main/java/com/tikal/jenkins/plugins/multijob/StatusJob.java
- src/main/java/com/tikal/jenkins/plugins/multijob/SubTask.java
- src/main/java/com/tikal/jenkins/plugins/multijob/views/MultiJobView.java
- src/main/java/com/tikal/jenkins/plugins/multijob/views/PhaseWrapper.java
This change will support pipeline jobs in a multijob job. Change was originally suggested by Simon Weber in https://issues.jenkins-ci.org/browse/JENKINS-38825. Can you please review and merge the change.
Change-Id: I837bc6e757c7b0dbcc90ee52823540fb8c4df8f1
> Updating code to build pipeline using multijob

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuildSelector.java
This fix address the issue when subjob of multijob build
tries to use copy-artifact with "Which build" set to:
"Build triggered by current MultiJob build"
Job interrupts with following stacktrace:
```
ERROR: Build step failed with exception
java.lang.ClassCastException: hudson.model.Cause$UserIdCause cannot be cast to hudson.model.Cause$UpstreamCause
at com.tikal.jenkins.plugins.multijob.MultiJobBuildSelector.getBuild(MultiJobBuildSelector.java:44)
at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:420)
at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
at …
```
> fix multijob build selector for copy-artifacts

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
- src/main/java/com/tikal/jenkins/plugins/multijob/QuietPeriodCalculator.java
- src/main/java/com/tikal/jenkins/plugins/multijob/SubTask.java
- src/main/java/com/tikal/jenkins/plugins/multijob/views/PhaseWrapper.java
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuilder/config.jelly
- src/main/webapp/help-quiet-period-calculator.html
- src/test/java/com/tikal/jenkins/plugins/multijob/test/ConditionalPhaseTest.java
- src/test/java/com/tikal/jenkins/plugins/multijob/test/QuietPeriodCalculatorTest.java
To avoid massive load on out database server this configuration
makes it possible to delay the execution of all or some sub-jobs
based on the sub-job index.
Should fix #158 as well.
> Calculate a sub-job's quiet time based on a Groovy expression parameter.

- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuild/table.jelly
- src/main/resources/com/tikal/jenkins/plugins/multijob/views/ConsoleColumn/column.jelly
The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this change.
Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @yorammi 
Thanks in advance!
> Adapt icon path removal from core

- Jenkinsfile
- pom.xml
- src/main/java/com/tikal/jenkins/plugins/multijob/FileBuildParameters.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuild.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuildSelector.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuilder.java
- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobProject.java
- src/main/java/com/tikal/jenkins/plugins/multijob/PhaseJobsConfig.java
- src/main/java/com/tikal/jenkins/plugins/multijob/PredefinedBuildParameters.java
- src/main/java/com/tikal/jenkins/plugins/multijob/views/MultiJobListViewColumn.java
- src/main/java/com/tikal/jenkins/plugins/multijob/views/MultiJobView.java
Hi, I see this plugin has been deprecated recently. We have quite a few jobs that rely on it, so I was curious what it would take to bring it up to the latest plugin version vs converting to pipelines. It ended up being straightforward, so I thought I'd submit this PR to see if there was interest in merging.
The bulk of the work was in getting compliant with the spotbugs rules that come enabled by default in parent version 4.40. These are mainly around preventing NPEs, exception handling, and stream closing.
I chose to use Jenkins 2.319.3 as a baseline based on [the guide](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/).
I bumped several plugins that were not included in the plugins-bom based on [security …
> Upgrade parent, plugin dependencies

- src/main/resources/com/tikal/jenkins/plugins/multijob/views/ConsoleColumn/column.jelly
Fixes: https://github.com/jenkinsci/tikal-multijob-plugin/issues/282
The solution is the same as the one used in: https://github.com/jenkinsci/jenkins/blob/53d91017ca491732635e0c1ed67c59794eb0d060/core/src/main/resources/lib/hudson/ballColorTd.jelly#L61. The `icon-` prefix is extraneous; this PR removes it.
> fix: Display console icon in job table correctly

- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuild/table.jelly
All I want is a green ball, but that plugin is deprecated. Might as well migrate to svg here.
> Replaced png build status icons with svg

- src/main/java/com/tikal/jenkins/plugins/multijob/MultiJobBuild.java
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuild/main.jelly
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobBuild/table.jelly
`table.jelly` view includes itself recursively to expand the downstream multijobs triggered from the current multijob. When the multijob has reference loops it goes into an infinite recursion. To prevent that I added upstream builds tracking.
Tested manually
> Prevent infinite loop in multijob view, fixes #255

- pom.xml
POM dependencies got a bit bushy, so I pared them down:
- `jenkins-bom` is managed by `plugin`
- `mailer` dropped as I don't see it used anywhere
- `parameterized-trigger`, `conditional-buildstep`, `maven-plugin`, `copyartifact`, and `matrix-project` versions are managed in `io.jenkins.tools.bom`
- `workflow-job`, `workflow-cps`, and `workflow-basic-steps` test dependencies are managed in `io.jenkins.tools.bom`
- `commons-net` conflict resolved in `maven-plugin` instead of `jenkins-test-harness`
- removed unnecessary exclusions from `maven-plugin`
- sorted dependencies
Used a locally built version in our organization
> Removed pinned dependencies versions where not necessary

- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobTestResults/index.jelly
- src/main/resources/com/tikal/jenkins/plugins/multijob/MultiJobTestResults/show-hide-failure-summary.js
[JENKINS-73964](https://issues.jenkins.io/browse/JENKINS-73964)
Very similar JS extraction to: 
- https://github.com/jenkinsci/junit-plugin/pull/654
-Using same steps for testing as #375 
[statusQuo](https://www.loom.com/share/8434ae745ce8457bafed8a8720bd4b34)
[csp-report-only](https://www.loom.com/share/99118f6999fe4b11b8b1db250e41dd5f)
[csp-restrictive](https://www.loom.com/share/9616744b8393455a93583f49a68d5a99)
> [JENKINS-73964] Extract event handlers in `MultiJobTestResults/index.jelly`
